version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: medical-clinic
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - local:/var/lib/postgresql/data
  medical-clinic:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/medical-clinic
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
volumes:
  postgres_db:
    driver: local